[package]
name = "rim"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio-tungstenite = "*"
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3"
rocket = "0.5.0-rc.2"
mysql = "22.2.0"